version: "3.8"
services:
  mongodb:
    image: mongo:5.0
    container_name: mongodb
    volumes:
      - ../data/mongo:/data/db

  elasticsearch:
    image: elasticsearch:7.17.6
    container_name: elastic
    volumes:
      - ../data/elastic:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  graylog:
    image: graylog/graylog:5.1.1
    container_name: graylog
    restart: always
    volumes:
      - ./config/graylog/graylog.conf:/usr/share/graylog/data/config/graylog.conf
    environment:
      - "GRAYLOG_PASSWORD_SECRET=${GRAYLOG_PASSWORD_SECRET}"
      # Password: admin
      - "GRAYLOG_ROOT_PASSWORD_SHA2=${GRAYLOG_ROOT_PASSWORD_SHA2}"
      - "GRAYLOG_HTTP_BIND_ADDRESS=${GRAYLOG_HTTP_BIND_ADDRESS}"
      - "GRAYLOG_HTTP_EXTERNAL_URI=${GRAYLOG_HTTP_EXTERNAL_URI}"
    links:
      - mongodb:mongo
      - elasticsearch
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - "${GRAYLOG_WEB_PORT}:7555"
      - 1514:1514
      - 1514:1514/udp
      - 12201:12201
      - 12201:12201/udp

  fluent-bit-checkout:
    image: fluent/fluent-bit
    container_name: fluent_bit_checkout
    hostname: fluent-bit
    ulimits:
      memlock:
        soft: -1
        hard: -1
    cap_drop:
      - NET_ADMIN
      - SYS_ADMIN
    ports:
      - 127.0.0.1:24224:24224
      - 127.0.0.1:24224:24224/udp
    volumes:
      - ./config/fluentd/checkout.conf:/fluent-bit/etc/fluent-bit.conf

  fluent-bit-loms:
    image: fluent/fluent-bit
    container_name: fluent_bit_loms
    hostname: fluent-bit
    ulimits:
      memlock:
        soft: -1
        hard: -1
    cap_drop:
      - NET_ADMIN
      - SYS_ADMIN
    ports:
      - 127.0.0.1:24225:24224
      - 127.0.0.1:24225:24224/udp
    volumes:
      - ./config/fluentd/loms.conf:/fluent-bit/etc/fluent-bit.conf

  fluent-bit-notifications:
    image: fluent/fluent-bit
    container_name: fluent_bit_notifications
    hostname: fluent-bit
    ulimits:
      memlock:
        soft: -1
        hard: -1
    cap_drop:
      - NET_ADMIN
      - SYS_ADMIN
    ports:
      - 127.0.0.1:24226:24224
      - 127.0.0.1:24226:24224/udp
    volumes:
      - ./config/fluentd/notifications.conf:/fluent-bit/etc/fluent-bit.conf

volumes:
  mongodb:
  elasticsearch:
