// Code generated by mockery v2.30.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "route256/checkout/internal/model"
)

// ProductChecker is an autogenerated mock type for the ProductChecker type
type ProductChecker struct {
	mock.Mock
}

// GetProducts provides a mock function with given fields: ctx, goods
func (_m *ProductChecker) GetProducts(ctx context.Context, goods []model.CartItem) ([]model.Good, error) {
	ret := _m.Called(ctx, goods)

	var r0 []model.Good
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []model.CartItem) ([]model.Good, error)); ok {
		return rf(ctx, goods)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []model.CartItem) []model.Good); ok {
		r0 = rf(ctx, goods)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Good)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []model.CartItem) error); ok {
		r1 = rf(ctx, goods)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewProductChecker creates a new instance of ProductChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProductChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProductChecker {
	mock := &ProductChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
